dispatching translation finished event once ALL batches have been translated
tilde-nlp/website-translator pull request #24
Opened 2024-07-04 14:51 UTC by alexattt

šo dispatched event savukārt ar puppeteer palīdzību varēs ķert un hopefully sagaidīt, tas tad apzīmēs to, ka tulkošana ir galā un jaunu translate requestu nebūs

2024-07-05 11:20 UTC, davisrtilde requested changes

2024-07-05 11:34 UTC, alexattt commented on src/js/lib/AsyncTranslator.ts
> +    this.batchesTotal = batches.length;
tā arī sanāk, ka pārraksta, jo skaitot klāt sanāks dublēšana, bet tā widgets skatās, kad parādās jauni items tulkošanai, no tiem taisa batches

2024-07-05 11:37 UTC, alexattt commented on src/js/lib/AsyncTranslator.ts
> +      document.dispatchEvent(this.translationFinishedEvent);
nederēs tas moments, tur katram batch logo atsevišķi, tātad sanāk, ja ir 4 batches for translate, mums pēc pirmā iztulkošanas tiks dispatched event un visi citi batches netiks sagaidīti

2024-07-05 11:40 UTC, alexattt commented on src/js/lib/AsyncTranslator.ts
> +      document.dispatchEvent(this.translationFinishedEvent);
identiski ar to getProgress, tur atgriež 1 katram batch, kura tulkošana tiek pabeigta

2024-07-05 12:29 UTC, davisrtilde commented on src/js/lib/AsyncTranslator.ts
> +      document.dispatchEvent(this.translationFinishedEvent);
Kāds tad ir tas workflow, sinhroni izsauksies `onTranslationItemDiscovered` līdz `this.getBatches(items)` atgriezīs tukšu sarakstu, kas nozīmē, ka vairāk nebūs nekas jātulko? Un kā ir ar dinamiskajiem elementiem - ja pēc 10s parādās lapā teksts, kas jātulko?

2024-07-15 07:17 UTC, alexattt commented on src/js/lib/AsyncTranslator.ts
> +    this.batchesTotal = batches.length;
pārsaucu

2024-07-15 09:12 UTC, davisrtilde approved these changes

2024-07-16 09:01 UTC, merged